#!/bin/sh
#
# postinstall script for the MySQL Startup Item Installation package
#
# This script modifies /etc/hostconfig in the following ways:
#
# - On Mac OS X Server, it disables the startup of the default MySQL
#   installation by changing the "MYSQL" start variable to "-NO-".
# - If not existent already, it adds a "MYSQLCOM" start variable, which
#   defaults to "-YES-". An already existing MYSQLCOM variable will remain
#   untouched.
#
# Copyright 2003-2008 MySQL AB, 2008-2012 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

CONFFILE="/etc/hostconfig"
TMPFILE=`basename $CONFFILE` || exit 1
TMPFILE=`mktemp -t $TMPFILE.tmp` || exit 1

test -e $CONFFILE || exit 1

# Disable the startup of the default MySQL installation that ships with
# Mac OS X Server to avoid conflicts with our installation on bootup
sed -e s/^MYSQL=-YES-/MYSQL=-NO-/g < $CONFFILE > $TMPFILE

# Add our MYSQLCOM startup variable (enabled by default)	#2>&1 表示把标准出错重定向到标准输出(0 stdin;1 stdou;2 stderr)
grep -q "^MYSQLCOM" $CONFFILE > /dev/null 2>&1
if [ $? -ne 0 ] ; then		#$?上个命令状态，0或者1
	echo "MYSQLCOM=-YES-" >> $TMPFILE
fi

# Install the modified file into the default location
cp -f $CONFFILE $CONFFILE~ || exit 1
mv -f $TMPFILE $CONFFILE || echo "Error while installing new $CONFFILE!"
chmod 644 $CONFFILE



CONFFILE="/etc/hostconfig"
TMPFILE=`basename $CONFFILE` || exit 1
TMPFILE=`mktemp -t $TMPFILE.tmp` || exit 1
echo $TMPFILE